//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ValueObject
{   
    public class Support
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public Nullable<int> Type { get; set; }
        public string Nick { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> Status { get; set; }
        public bool isDel { get; set; }
    }
}
